---
name: CI
on:
  pull_request: {}
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  verify-generated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Generate all
        run: |
          make generate-all
