---
name: CI
on:
  pull_request: {}
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  verify-generated:
    steps:
      - name: Generate all
        run: |
          make generate-all
